 <footer class="footer">
        <div class="footer-content">
            <div class="links">
                <a href="#" class="pricing">Pricing</a>
                <a href="jobs.php" class="careers">Careers</a>
                <a href="#" class="term">Term</a>
                <a href="https://github.com/quangDungnguyen2004/Project-Part-1-of-2.git" target="_blank" class="github">GitHub</a>
                <a href="https://earthlings-team.atlassian.net/jira/software/projects/SCRUM/summary?atlOrigin=eyJpIjoiMTAxNDgwMGYzMDk1NDI2MmI4NTk1NGYzZTFjNjcyZmMiLCJwIjoiaiJ9" target="_blank" class="jira">Jira</a>
            </div>
            <div class="copyright">Copyright © 2025 Earthling. All rights reserved.</div>
        </div>
    </footer>
</body>
</html>
